language: node_js

node_js :
  - "10.15.1"

cache:
directories:
  - "node_modules"

services:
  - postgresql

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - npm i -g sequelize-cli

script:
  - npm run test

after_script:
  - npm run coverage

language: node_js

cache:
directories:
  - "node_modules"

services:
  - postgresql

script:
  - npm run test

after_script:
  - npm run coverage
